### PR TITLE
Added loading options from pytest.ini

### PR DESCRIPTION
**Pull request by bendtherules**
Things Added:
1. CollectIniPathPlugin which acts as a pytest plugin and does a dry-run of pytest to capture the ini path in CollectorIniPath.pytest_ini_path class variable
2. Load "pytest-watch" section from that ini and read the options
3. Mix that option with cmdline args, giving preference to cmdline values

Todo:
1. Add proper tests for ini args loading
2. <strike> Refactor string and boolean variable loading code to diff. func, whole thing looks bad now </strike>

### CODE REVIEW

**Comment by bendtherules** [comment]
PR for issue #20

**Comment by bendtherules** [comment]
Should I move the ini path collector to a new module, it looks a bit out of place in command.py

**Comment by bendtherules** [comment]
Does it look ok, @joeyespo ?

**Comment by joeyespo** [comment]
Looks good. Ready to merge?

**Comment by bendtherules** [comment]
Yes.

**Comment by joeyespo** [comment]
:+1: Thanks, @bendtherules!

**Pull request merged**
