### PR TITLE
Wait for pdb if it's passed to pytest_args

### PR DESCRIPTION
**Pull request by remcohaszing**
This prevents multiple pdb sessions from running simultaneously when
running:

        pytest-watch -- --pdb

Previously this could result into annoying behaviour.

### CODE REVIEW

**Comment by blueyed** [comment]
LGTM, I think this bugged my already a few times.

**Comment by joeyespo** [comment]
Why not run `pytest-watch --pdb`? That was added in to handle this case.

I'm all for reducing frustration and confusion though :+1: And this is well-aligned with #57.

Thanks, @remcohaszing!

**Comment by remcohaszing** [comment]
Because it takes so many keypresses to properly modify `ptw -- --maxfail 1 -vv` ;)

**Comment by blueyed** [comment]
@remcohaszing 
You can use `-x` instead of `--maxfail 1` btw (AFAICS).

**Comment by remcohaszing** [comment]
@blueyed I didn't know, thanks for the tip. :smile_cat:

**Pull request merged**
